// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0qDcGiR0dx71aHwai08J81hwGJGlcZuU',
    appId: '1:228510698510:web:ae36555be17fba741b405f',
    messagingSenderId: '228510698510',
    projectId: 'fir-exampleapp-eb444',
    authDomain: 'fir-exampleapp-eb444.firebaseapp.com',
    storageBucket: 'fir-exampleapp-eb444.firebasestorage.app',
    measurementId: 'G-Y4Y821HSPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8usuwf6npLfAOFtjAekpBM28sNJLPXp8',
    appId: '1:228510698510:android:77ad804e07fba3371b405f',
    messagingSenderId: '228510698510',
    projectId: 'fir-exampleapp-eb444',
    storageBucket: 'fir-exampleapp-eb444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSiepqbLeJkyMiXwkVOFRQRufthNRiBZ8',
    appId: '1:228510698510:ios:5b3f942f33670b741b405f',
    messagingSenderId: '228510698510',
    projectId: 'fir-exampleapp-eb444',
    storageBucket: 'fir-exampleapp-eb444.firebasestorage.app',
    iosBundleId: 'com.nayeem.firebaseAppExample',
  );
}
